const CartActionTypes = {
    TOGGELE_CART_HIDDEN: 'TOGGELE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    REMOVE_ITEM: 'REMOVE_TEIM',
    CLEAR_CART: 'CLEAR_CART'
};

export default CartActionTypes;